spring:
  datasource:
    url: jdbc:mysql://db:3306/nexus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: reader
    password: 123456
    druid:
      initial-size: 5 # Configuration property
      min-idle: 10 # Configuration property
      max-active: 20 # Configuration property
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # Configuration property
      stat-view-servlet: # Configuration property
        login-username: druid
        login-password: druid
  data:
    redis:
      host: redis # Configuration property
      database: 0 # Configuration property
      port: 6379 # Configuration property
      password: # Configuration property
      timeout: 300ms # Configuration property

minio:
  endpoint: http://192.168.3.101:9090 # Configuration property
  bucketName: nexus # Configuration property
  accessKey: minioadmin # Configuration property
  secretKey: minioadmin # Configuration property

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.nexusengine.core: info

logstash:
  host: logstash