UPDATE ums_role SET name = 'Customer Support', description = 'Handles customer queries and support tickets.' WHERE id = 3;
UPDATE ums_role SET name = 'Order Manager', description = 'Manages and processes customer orders.' WHERE id = 4;
UPDATE ums_role SET name = 'Product Manager', description = 'Manages product catalog and inventory.' WHERE id = 5;
UPDATE ums_role SET name = 'Marketing Manager', description = 'Manages promotions and marketing campaigns.' WHERE id = 100;
UPDATE ums_role SET name = 'Content Editor', description = 'Manages CMS and website content.' WHERE id = 101;
UPDATE ums_role SET name = 'Financial Analyst', description = 'Handles financial reporting and analytics.' WHERE id = 102;
UPDATE ums_role SET name = 'HR Manager', description = 'Manages human resources and admin staff.' WHERE id = 103;
UPDATE ums_role SET name = 'Operations Lead', description = 'Oversees general operations.' WHERE id = 104;
UPDATE ums_role SET name = 'Sales Manager', description = 'Manages B2B sales and large accounts.' WHERE id = 200;
UPDATE ums_role SET name = 'QA Tester', description = 'Ensures quality assurance for the platform.' WHERE id = 201;
UPDATE ums_role SET name = 'Technical Support', description = 'Provides L2 technical support.' WHERE id = 202;
UPDATE ums_role SET name = 'System Operator', description = 'Handles system infrastructure.' WHERE id = 203;
UPDATE ums_role SET name = 'Auditor', description = 'Performs internal audits and compliance checks.' WHERE id = 204;
UPDATE ums_role SET name = 'Compliance Officer', description = 'Ensures legal and policy compliance.' WHERE id = 205;
UPDATE ums_role SET name = 'Logistics Coordinator', description = 'Manages shipping and vendor logistics.' WHERE id = 206;
UPDATE ums_role SET name = 'Customer Success Manager', description = 'Ensures client satisfaction.' WHERE id = 207;
UPDATE ums_role SET name = 'Partner Relations Manager', description = 'Handles B2B partnerships.' WHERE id = 208;
UPDATE ums_role SET name = 'Data Analyst', description = 'Provides data insights and reports.' WHERE id = 209;
