TRUNCATE TABLE cms_subject_category CASCADE;
TRUNCATE TABLE cms_help_category CASCADE;
TRUNCATE TABLE cms_help CASCADE;
TRUNCATE TABLE cms_topic_category CASCADE;
TRUNCATE TABLE oms_company_address CASCADE;
TRUNCATE TABLE oms_order_return_reason CASCADE;
TRUNCATE TABLE oms_order_setting CASCADE;
TRUNCATE TABLE pms_album CASCADE;
TRUNCATE TABLE pms_album_pic CASCADE;
TRUNCATE TABLE sms_flash_promotion CASCADE;
TRUNCATE TABLE sms_flash_promotion_session CASCADE;
TRUNCATE TABLE ums_member_level CASCADE;
TRUNCATE TABLE ums_integration_consume_setting CASCADE;
TRUNCATE TABLE ums_member_member_tag_relation CASCADE;
TRUNCATE TABLE ums_member_rule_setting CASCADE;
TRUNCATE TABLE ums_member_statistics_info CASCADE;
TRUNCATE TABLE ums_member_tag CASCADE;
TRUNCATE TABLE ums_member_task CASCADE;

ALTER TABLE cms_subject_category ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cms_help_category ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cms_help ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cms_topic_category ALTER COLUMN id RESTART WITH 1;
ALTER TABLE oms_company_address ALTER COLUMN id RESTART WITH 1;
ALTER TABLE oms_order_return_reason ALTER COLUMN id RESTART WITH 1;
ALTER TABLE oms_order_setting ALTER COLUMN id RESTART WITH 1;
ALTER TABLE pms_album ALTER COLUMN id RESTART WITH 1;
ALTER TABLE pms_album_pic ALTER COLUMN id RESTART WITH 1;
ALTER TABLE sms_flash_promotion ALTER COLUMN id RESTART WITH 1;
ALTER TABLE sms_flash_promotion_session ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_member_level ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_integration_consume_setting ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_member_rule_setting ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_member_statistics_info ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_member_tag ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ums_member_task ALTER COLUMN id RESTART WITH 1;
