-- V14__normalize_product_media.sql
-- FAANG 1NF Normalization: Moving comma-separated album_pics into a dedicated table

CREATE TABLE pms_product_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    media_type VARCHAR(50) DEFAULT 'IMAGE',
    media_url VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    CONSTRAINT fk_pms_product_media_product_id FOREIGN KEY (product_id) REFERENCES pms_product(id) ON DELETE CASCADE
);

-- Migrate existing data (PostgreSQL 10+ compatible string splitting)
INSERT INTO pms_product_media (product_id, media_url, sort_order)
SELECT 
    id as product_id,
    unnest(string_to_array(NULLIF(album_pics, ''), ',')) as media_url,
    0 as sort_order
FROM pms_product
WHERE album_pics IS NOT NULL AND album_pics != '';

-- Fix sort_order so it increments sequentially per product
WITH CTE AS (
    SELECT id, row_number() over (partition by product_id order by id) - 1 as new_sort_order
    FROM pms_product_media
)
UPDATE pms_product_media SET sort_order = CTE.new_sort_order FROM CTE WHERE pms_product_media.id = CTE.id;

-- Drop the 1NF violating column
ALTER TABLE pms_product DROP COLUMN album_pics;
