-- V17__payment_idempotency.sql
-- FAANG Modular Monolith: Adding Webhook Idempotency for Partial Refunds & Payments

CREATE TABLE oms_payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    transaction_id VARCHAR(255) NOT NULL,
    transaction_type VARCHAR(50) NOT NULL, -- 'PAYMENT' or 'REFUND'
    amount NUMERIC(38, 2) NOT NULL,
    status VARCHAR(50) NOT NULL, -- 'PENDING', 'SUCCESS', 'FAILED'
    webhook_payload JSONB,
    create_time TIMESTAMP DEFAULT NOW(),
    CONSTRAINT uk_oms_payment_transaction_id UNIQUE (transaction_id)
);

-- Index for fast order lookups
CREATE INDEX idx_oms_payment_order_id ON oms_payment_transaction(order_id);
