ALTER TABLE pms_member_price ADD CONSTRAINT fk_pms_member_price_member_level_id FOREIGN KEY (member_level_id) REFERENCES ums_member_level(id) ON DELETE CASCADE;
ALTER TABLE ums_menu ADD CONSTRAINT fk_ums_menu_parent_id FOREIGN KEY (parent_id) REFERENCES ums_menu(id) ON DELETE CASCADE;
ALTER TABLE pms_product ADD CONSTRAINT fk_pms_product_feight_template_id FOREIGN KEY (feight_template_id) REFERENCES pms_feight_template(id) ON DELETE SET NULL;
ALTER TABLE pms_product ADD CONSTRAINT fk_pms_product_product_attribute_category_id FOREIGN KEY (product_attribute_category_id) REFERENCES pms_product_attribute_category(id) ON DELETE SET NULL;
ALTER TABLE ums_role_permission_relation ADD CONSTRAINT fk_ums_role_permission_relation_permission_id FOREIGN KEY (permission_id) REFERENCES ums_permission(id) ON DELETE CASCADE;
ALTER TABLE cms_prefrence_area_product_relation ADD CONSTRAINT fk_cms_prefrence_area_product_relation_prefrence_area_id FOREIGN KEY (prefrence_area_id) REFERENCES cms_prefrence_area(id) ON DELETE CASCADE;
ALTER TABLE cms_topic_comment ADD CONSTRAINT fk_cms_topic_comment_topic_id FOREIGN KEY (topic_id) REFERENCES cms_topic(id) ON DELETE CASCADE;
ALTER TABLE ums_role_menu_relation ADD CONSTRAINT fk_ums_role_menu_relation_menu_id FOREIGN KEY (menu_id) REFERENCES ums_menu(id) ON DELETE CASCADE;
ALTER TABLE sms_flash_promotion_product_relation ADD CONSTRAINT fk_sms_flash_promotion_product_relation_flash_promotion_id FOREIGN KEY (flash_promotion_id) REFERENCES sms_flash_promotion(id) ON DELETE CASCADE;
ALTER TABLE sms_flash_promotion_product_relation ADD CONSTRAINT fk_sms_flash_promotion_product_relation_flash_promotion_session_id FOREIGN KEY (flash_promotion_session_id) REFERENCES sms_flash_promotion_session(id) ON DELETE CASCADE;
ALTER TABLE pms_product_attribute_value ADD CONSTRAINT fk_pms_product_attribute_value_product_attribute_id FOREIGN KEY (product_attribute_id) REFERENCES pms_product_attribute(id) ON DELETE CASCADE;
ALTER TABLE oms_order_item ADD CONSTRAINT fk_oms_order_item_product_sku_id FOREIGN KEY (product_sku_id) REFERENCES pms_sku_stock(id) ON DELETE CASCADE;
ALTER TABLE pms_product_category ADD CONSTRAINT fk_pms_product_category_parent_id FOREIGN KEY (parent_id) REFERENCES pms_product_category(id) ON DELETE CASCADE;
ALTER TABLE pms_album_pic ADD CONSTRAINT fk_pms_album_pic_album_id FOREIGN KEY (album_id) REFERENCES pms_album(id) ON DELETE CASCADE;
ALTER TABLE pms_review ADD CONSTRAINT fk_pms_review_parent_id FOREIGN KEY (parent_id) REFERENCES pms_review(id) ON DELETE CASCADE;
ALTER TABLE cms_subject ADD CONSTRAINT fk_cms_subject_category_id FOREIGN KEY (category_id) REFERENCES cms_subject_category(id) ON DELETE SET NULL;
ALTER TABLE oms_order_return_apply ADD CONSTRAINT fk_oms_order_return_apply_company_address_id FOREIGN KEY (company_address_id) REFERENCES oms_company_address(id) ON DELETE SET NULL;
ALTER TABLE pms_product_category_attribute_relation ADD CONSTRAINT fk_pms_product_category_attribute_relation_product_attribute_id FOREIGN KEY (product_attribute_id) REFERENCES pms_product_attribute(id) ON DELETE CASCADE;
ALTER TABLE cms_help ADD CONSTRAINT fk_cms_help_category_id FOREIGN KEY (category_id) REFERENCES cms_help_category(id) ON DELETE SET NULL;
ALTER TABLE pms_comment_replay ADD CONSTRAINT fk_pms_comment_replay_comment_id FOREIGN KEY (comment_id) REFERENCES pms_comment(id) ON DELETE CASCADE;
ALTER TABLE ums_resource ADD CONSTRAINT fk_ums_resource_category_id FOREIGN KEY (category_id) REFERENCES ums_resource_category(id) ON DELETE SET NULL;
ALTER TABLE ums_member_member_tag_relation ADD CONSTRAINT fk_ums_member_member_tag_relation_tag_id FOREIGN KEY (tag_id) REFERENCES ums_member_tag(id) ON DELETE CASCADE;
ALTER TABLE ums_member ADD CONSTRAINT fk_ums_member_member_level_id FOREIGN KEY (member_level_id) REFERENCES ums_member_level(id) ON DELETE SET NULL;
ALTER TABLE cms_topic ADD CONSTRAINT fk_cms_topic_category_id FOREIGN KEY (category_id) REFERENCES cms_topic_category(id) ON DELETE SET NULL;
ALTER TABLE oms_cart_item ADD CONSTRAINT fk_oms_cart_item_product_sku_id FOREIGN KEY (product_sku_id) REFERENCES pms_sku_stock(id) ON DELETE CASCADE;
ALTER TABLE pms_product_attribute ADD CONSTRAINT fk_pms_product_attribute_product_attribute_category_id FOREIGN KEY (product_attribute_category_id) REFERENCES pms_product_attribute_category(id) ON DELETE CASCADE;
ALTER TABLE ums_admin_permission_relation ADD CONSTRAINT fk_ums_admin_permission_relation_permission_id FOREIGN KEY (permission_id) REFERENCES ums_permission(id) ON DELETE CASCADE;
