UPDATE ums_menu SET title = 'Merchandise' WHERE id = 1;
UPDATE ums_menu SET title = 'Product List' WHERE id = 2;
UPDATE ums_menu SET title = 'Add Product' WHERE id = 3;
UPDATE ums_menu SET title = 'Product Category' WHERE id = 4;
UPDATE ums_menu SET title = 'Product Type' WHERE id = 5;
UPDATE ums_menu SET title = 'Brand Management' WHERE id = 6;
UPDATE ums_menu SET title = 'Order' WHERE id = 7;
UPDATE ums_menu SET title = 'Order List' WHERE id = 8;
UPDATE ums_menu SET title = 'Order Settings' WHERE id = 9;
UPDATE ums_menu SET title = 'Return Request Processing' WHERE id = 10;
UPDATE ums_menu SET title = 'Return Reason Settings' WHERE id = 11;
UPDATE ums_menu SET title = 'Marketing' WHERE id = 12;
UPDATE ums_menu SET title = 'Flash Sale Activity List' WHERE id = 13;
UPDATE ums_menu SET title = 'Coupon List' WHERE id = 14;
UPDATE ums_menu SET title = 'Brand Recommendation' WHERE id = 16;
UPDATE ums_menu SET title = 'New Product Recommendations' WHERE id = 17;
UPDATE ums_menu SET title = 'Popular Recommendation' WHERE id = 18;
UPDATE ums_menu SET title = 'Topic Recommendations' WHERE id = 19;
UPDATE ums_menu SET title = 'Advertisement List' WHERE id = 20;
UPDATE ums_menu SET title = 'Permissions' WHERE id = 21;
UPDATE ums_menu SET title = 'User List' WHERE id = 22;
UPDATE ums_menu SET title = 'Role List' WHERE id = 23;
UPDATE ums_menu SET title = 'Menu List' WHERE id = 24;
UPDATE ums_menu SET title = 'Resource List' WHERE id = 25;
