TRUNCATE TABLE pms_product_attribute_category CASCADE;
TRUNCATE TABLE pms_product_attribute CASCADE;
TRUNCATE TABLE pms_product_category_attribute_relation CASCADE;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (2, 'Smartwatches Attributes', 1, 4);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (1, 2, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (2, 1);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (2, 2, 'Strap Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (3, 2, 'Display Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (2, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (4, 2, 'GPS', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (2, 4);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (5, 2, 'Water Resistance', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (2, 5);
UPDATE pms_product SET product_attribute_category_id = 2 WHERE product_category_id = 2;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (3, 'Laptops Attributes', 3, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (6, 3, 'RAM', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (3, 6);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (7, 3, 'Storage', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (3, 7);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (8, 3, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (3, 8);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (9, 3, 'Processor', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (3, 9);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (10, 3, 'Screen Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (3, 10);
UPDATE pms_product SET product_attribute_category_id = 3 WHERE product_category_id = 3;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (4, 'Cameras Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (11, 4, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (4, 11);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (12, 4, 'Resolution', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (4, 12);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (13, 4, 'Sensor Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (4, 13);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (14, 4, 'Connectivity', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (4, 14);
UPDATE pms_product SET product_attribute_category_id = 4 WHERE product_category_id = 4;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (5, 'Monitors Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (15, 5, 'Size (inches)', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (5, 15);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (16, 5, 'Resolution', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (5, 16);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (17, 5, 'Refresh Rate', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (5, 17);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (18, 5, 'Panel Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (5, 18);
UPDATE pms_product SET product_attribute_category_id = 5 WHERE product_category_id = 5;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (6, 'Smartphones Attributes', 2, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (19, 6, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (6, 19);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (20, 6, 'Storage', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (6, 20);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (21, 6, 'RAM', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (6, 21);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (22, 6, 'Screen Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (6, 22);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (23, 6, 'Camera', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (6, 23);
UPDATE pms_product SET product_attribute_category_id = 6 WHERE product_category_id = 6;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (7, 'Headphones & Earbuds Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (24, 7, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (7, 24);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (25, 7, 'Connectivity', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (7, 25);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (26, 7, 'ANC', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (7, 26);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (27, 7, 'Battery Life', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (7, 27);
UPDATE pms_product SET product_attribute_category_id = 7 WHERE product_category_id = 7;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (8, 'Tablets Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (28, 8, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (8, 28);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (29, 8, 'Storage', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (8, 29);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (30, 8, 'RAM', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (8, 30);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (31, 8, 'Screen Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (8, 31);
UPDATE pms_product SET product_attribute_category_id = 8 WHERE product_category_id = 8;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (9, 'Keyboards & Mice Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (32, 9, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (9, 32);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (33, 9, 'Connectivity', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (9, 33);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (34, 9, 'Layout', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (9, 34);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (35, 9, 'Switch Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (9, 35);
UPDATE pms_product SET product_attribute_category_id = 9 WHERE product_category_id = 9;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (11, 'Women''s Clothing Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (36, 11, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (11, 36);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (37, 11, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (11, 37);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (38, 11, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (11, 38);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (39, 11, 'Fit', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (11, 39);
UPDATE pms_product SET product_attribute_category_id = 11 WHERE product_category_id = 11;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (12, 'Men''s Clothing Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (40, 12, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (12, 40);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (41, 12, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (12, 41);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (42, 12, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (12, 42);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (43, 12, 'Fit', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (12, 43);
UPDATE pms_product SET product_attribute_category_id = 12 WHERE product_category_id = 12;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (13, 'Accessories Attributes', 2, 1);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (44, 13, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (13, 44);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (45, 13, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (13, 45);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (46, 13, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (13, 46);
UPDATE pms_product SET product_attribute_category_id = 13 WHERE product_category_id = 13;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (14, 'Footwear Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (47, 14, 'Size (US)', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (14, 47);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (48, 14, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (14, 48);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (49, 14, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (14, 49);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (50, 14, 'Shoe Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (14, 50);
UPDATE pms_product SET product_attribute_category_id = 14 WHERE product_category_id = 14;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (16, 'Kitchenware Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (51, 16, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (16, 51);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (52, 16, 'Capacity', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (16, 52);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (53, 16, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (16, 53);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (54, 16, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (16, 54);
UPDATE pms_product SET product_attribute_category_id = 16 WHERE product_category_id = 16;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (17, 'Furniture Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (55, 17, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (17, 55);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (56, 17, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (17, 56);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (57, 17, 'Dimensions', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (17, 57);
UPDATE pms_product SET product_attribute_category_id = 17 WHERE product_category_id = 17;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (18, 'Home Appliances Attributes', 2, 1);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (58, 18, 'Capacity', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (18, 58);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (59, 18, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (18, 59);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (60, 18, 'Power Consumption', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (18, 60);
UPDATE pms_product SET product_attribute_category_id = 18 WHERE product_category_id = 18;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (19, 'Kitchen Appliances Attributes', 2, 1);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (61, 19, 'Capacity', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (19, 61);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (62, 19, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (19, 62);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (63, 19, 'Power Consumption', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (19, 63);
UPDATE pms_product SET product_attribute_category_id = 19 WHERE product_category_id = 19;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (21, 'Skincare Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (64, 21, 'Skin Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (21, 64);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (65, 21, 'Ingredient', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (21, 65);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (66, 21, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (21, 66);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (67, 21, 'SPF', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (21, 67);
UPDATE pms_product SET product_attribute_category_id = 21 WHERE product_category_id = 21;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (22, 'Grooming Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (68, 22, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (22, 68);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (69, 22, 'Skin Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (22, 69);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (70, 22, 'Ingredient', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (22, 70);
UPDATE pms_product SET product_attribute_category_id = 22 WHERE product_category_id = 22;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (23, 'Makeup Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (71, 23, 'Shade', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (23, 71);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (72, 23, 'Finish', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (23, 72);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (73, 23, 'Skin Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (23, 73);
UPDATE pms_product SET product_attribute_category_id = 23 WHERE product_category_id = 23;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (24, 'Hair Care Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (74, 24, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (24, 74);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (75, 24, 'Hair Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (24, 75);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (76, 24, 'Ingredient', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (24, 76);
UPDATE pms_product SET product_attribute_category_id = 24 WHERE product_category_id = 24;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (26, 'Gym Equipment Attributes', 0, 4);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (77, 26, 'Weight', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (26, 77);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (78, 26, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (26, 78);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (79, 26, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (26, 79);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (80, 26, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (26, 80);
UPDATE pms_product SET product_attribute_category_id = 26 WHERE product_category_id = 26;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (27, 'Yoga Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (81, 27, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (27, 81);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (82, 27, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (27, 82);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (83, 27, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (27, 83);
UPDATE pms_product SET product_attribute_category_id = 27 WHERE product_category_id = 27;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (28, 'Running Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (84, 28, 'Size (US)', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (28, 84);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (85, 28, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (28, 85);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (86, 28, 'Cushioning', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (28, 86);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (87, 28, 'Shoe Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (28, 87);
UPDATE pms_product SET product_attribute_category_id = 28 WHERE product_category_id = 28;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (29, 'Outdoor Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (88, 29, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (29, 88);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (89, 29, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (29, 89);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (90, 29, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (29, 90);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (91, 29, 'Sport Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (29, 91);
UPDATE pms_product SET product_attribute_category_id = 29 WHERE product_category_id = 29;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (31, 'Non-Fiction Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (92, 31, 'Format', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (31, 92);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (93, 31, 'Language', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (31, 93);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (94, 31, 'Publication Year', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (31, 94);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (95, 31, 'Author', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (31, 95);
UPDATE pms_product SET product_attribute_category_id = 31 WHERE product_category_id = 31;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (32, 'Technology Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (96, 32, 'Format', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (32, 96);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (97, 32, 'Language', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (32, 97);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (98, 32, 'Publication Year', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (32, 98);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (99, 32, 'Author', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (32, 99);
UPDATE pms_product SET product_attribute_category_id = 32 WHERE product_category_id = 32;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (33, 'Notebooks & Supplies Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (100, 33, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (33, 100);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (101, 33, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (33, 101);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (102, 33, 'Paper Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (33, 102);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (103, 33, 'Page Count', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (33, 103);
UPDATE pms_product SET product_attribute_category_id = 33 WHERE product_category_id = 33;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (34, 'Fiction Attributes', 1, 3);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (104, 34, 'Format', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (34, 104);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (105, 34, 'Language', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (34, 105);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (106, 34, 'Publication Year', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (34, 106);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (107, 34, 'Author', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (34, 107);
UPDATE pms_product SET product_attribute_category_id = 34 WHERE product_category_id = 34;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (36, 'Pantry Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (108, 36, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (36, 108);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (109, 36, 'Vegetarian', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (36, 109);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (110, 36, 'Brand Origin', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (36, 110);
UPDATE pms_product SET product_attribute_category_id = 36 WHERE product_category_id = 36;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (37, 'Beverages Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (111, 37, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (37, 111);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (112, 37, 'Beverage Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (37, 112);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (113, 37, 'Flavor', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (37, 113);
UPDATE pms_product SET product_attribute_category_id = 37 WHERE product_category_id = 37;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (38, 'Snacks Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (114, 38, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (38, 114);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (115, 38, 'Flavor', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (38, 115);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (116, 38, 'Vegetarian', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (38, 116);
UPDATE pms_product SET product_attribute_category_id = 38 WHERE product_category_id = 38;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (39, 'Breakfast Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (117, 39, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (39, 117);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (118, 39, 'Ingredients', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (39, 118);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (119, 39, 'Vegetarian', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (39, 119);
UPDATE pms_product SET product_attribute_category_id = 39 WHERE product_category_id = 39;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (41, 'Car Accessories Attributes', 2, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (120, 41, 'Color', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (41, 120);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (121, 41, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (41, 121);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (122, 41, 'Material', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (41, 122);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (123, 41, 'Compatibility', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (41, 123);
UPDATE pms_product SET product_attribute_category_id = 41 WHERE product_category_id = 41;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (42, 'Replacement Parts Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (124, 42, 'Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (42, 124);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (125, 42, 'Vehicle Compatibility', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (42, 125);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (126, 42, 'Part Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (42, 126);
UPDATE pms_product SET product_attribute_category_id = 42 WHERE product_category_id = 42;
INSERT INTO pms_product_attribute_category (id, name, attribute_count, param_count) VALUES (43, 'Car Care Attributes', 1, 2);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (127, 43, 'Pack Size', 0, 0, '', 0, 0, 0, 0, 0, 0);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (43, 127);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (128, 43, 'Product Type', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (43, 128);
INSERT INTO pms_product_attribute (id, product_attribute_category_id, name, select_type, input_type, input_list, sort, filter_type, search_type, related_status, hand_add_status, type) VALUES (129, 43, 'Suitable For', 0, 0, '', 0, 0, 0, 0, 0, 1);
INSERT INTO pms_product_category_attribute_relation (product_category_id, product_attribute_id) VALUES (43, 129);
UPDATE pms_product SET product_attribute_category_id = 43 WHERE product_category_id = 43;