TRUNCATE TABLE pms_product_attribute_value CASCADE;
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (1, 4, 28, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (2, 4, 29, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (3, 4, 30, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (4, 4, 31, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (5, 10, 28, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (6, 10, 29, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (7, 10, 30, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (8, 10, 31, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (9, 20, 40, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (10, 20, 41, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (11, 20, 42, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (12, 20, 43, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (13, 19, 32, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (14, 19, 33, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (15, 19, 34, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (16, 19, 35, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (17, 24, 36, 'L,M,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (18, 24, 37, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (19, 24, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (20, 24, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (21, 17, 15, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (22, 17, 16, '2560x1440,3840x2160');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (23, 17, 17, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (24, 17, 18, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (25, 2, 19, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (26, 2, 20, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (27, 2, 21, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (28, 2, 22, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (29, 2, 23, 'Advanced Dual Camera');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (30, 3, 19, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (31, 3, 20, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (32, 3, 21, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (33, 3, 22, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (34, 3, 23, 'Advanced Dual Camera');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (35, 30, 47, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (36, 30, 48, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (37, 30, 49, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (38, 30, 50, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (39, 25, 36, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (40, 25, 37, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (41, 25, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (42, 25, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (43, 32, 47, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (44, 32, 48, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (45, 32, 49, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (46, 32, 50, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (47, 18, 15, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (48, 18, 16, '2560x1440,3840x2160');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (49, 18, 17, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (50, 18, 18, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (51, 12, 24, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (52, 12, 25, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (53, 12, 26, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (54, 12, 27, '24 Hours');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (55, 33, 47, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (56, 33, 48, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (57, 33, 49, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (58, 33, 50, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (59, 13, 24, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (60, 13, 25, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (61, 13, 26, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (62, 13, 27, '24 Hours');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (63, 16, 24, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (64, 16, 25, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (65, 16, 26, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (66, 16, 27, '24 Hours');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (67, 39, 55, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (68, 39, 56, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (69, 39, 57, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (70, 41, 55, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (71, 41, 56, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (72, 41, 57, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (73, 22, 40, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (74, 22, 41, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (75, 22, 42, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (76, 22, 43, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (77, 23, 40, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (78, 23, 41, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (79, 23, 42, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (80, 23, 43, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (81, 34, 44, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (82, 34, 45, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (83, 34, 46, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (84, 35, 44, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (85, 35, 45, 'L,M,S');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (86, 35, 46, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (87, 36, 44, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (88, 36, 45, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (89, 36, 46, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (90, 14, 1, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (91, 14, 2, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (92, 14, 3, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (93, 14, 4, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (94, 14, 5, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (95, 7, 6, '16GB,32GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (96, 7, 7, '1TB,512GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (97, 7, 8, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (98, 7, 9, 'Latest Gen Processor');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (99, 7, 10, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (100, 15, 11, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (101, 15, 12, '4K UHD');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (102, 15, 13, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (103, 15, 14, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (104, 5, 19, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (105, 5, 20, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (106, 5, 21, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (107, 5, 22, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (108, 5, 23, 'Advanced Dual Camera');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (109, 26, 36, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (110, 26, 37, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (111, 26, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (112, 26, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (113, 27, 36, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (114, 27, 37, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (115, 27, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (116, 27, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (117, 58, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (118, 58, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (119, 58, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (120, 58, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (121, 75, 68, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (122, 75, 69, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (123, 75, 70, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (124, 76, 68, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (125, 76, 69, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (126, 76, 70, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (127, 66, 71, '110 Porcelain,120 Classic Ivory,130 Buff Beige,220 Natural Beige');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (128, 66, 72, 'Matte Finish');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (129, 66, 73, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (130, 59, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (131, 59, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (132, 59, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (133, 59, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (134, 60, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (135, 60, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (136, 60, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (137, 60, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (138, 67, 71, '110 Porcelain,120 Classic Ivory,130 Buff Beige,220 Natural Beige');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (139, 67, 72, 'Matte Finish');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (140, 67, 73, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (141, 68, 71, '110 Porcelain,120 Classic Ivory,130 Buff Beige,220 Natural Beige');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (142, 68, 72, 'Matte Finish');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (143, 68, 73, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (144, 69, 71, '110 Porcelain,120 Classic Ivory,130 Buff Beige,220 Natural Beige');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (145, 69, 72, 'Matte Finish');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (146, 69, 73, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (147, 45, 61, '4L,6L');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (148, 45, 62, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (149, 45, 63, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (150, 46, 61, '3L,5L');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (151, 46, 62, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (152, 46, 63, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (153, 47, 61, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (154, 47, 62, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (155, 47, 63, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (156, 71, 74, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (157, 71, 75, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (158, 71, 76, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (159, 72, 74, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (160, 72, 75, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (161, 72, 76, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (162, 73, 74, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (163, 73, 75, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (164, 73, 76, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (165, 81, 77, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (166, 81, 78, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (167, 81, 79, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (168, 81, 80, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (169, 82, 77, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (170, 82, 78, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (171, 82, 79, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (172, 82, 80, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (173, 77, 84, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (174, 77, 85, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (175, 77, 86, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (176, 77, 87, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (177, 78, 84, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (178, 78, 85, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (179, 78, 86, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (180, 78, 87, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (181, 79, 84, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (182, 79, 85, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (183, 79, 86, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (184, 79, 87, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (185, 80, 84, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (186, 80, 85, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (187, 80, 86, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (188, 80, 87, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (189, 53, 51, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (190, 53, 52, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (191, 53, 53, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (192, 53, 54, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (193, 43, 58, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (194, 43, 59, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (195, 43, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (196, 48, 58, '6.5kg,8kg');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (197, 48, 59, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (198, 48, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (199, 49, 58, '6.5kg,8kg');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (200, 49, 59, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (201, 49, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (202, 61, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (203, 61, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (204, 61, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (205, 61, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (206, 62, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (207, 62, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (208, 62, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (209, 62, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (210, 63, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (211, 63, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (212, 63, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (213, 63, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (214, 100, 92, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (215, 100, 93, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (216, 100, 94, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (217, 100, 95, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (218, 104, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (219, 104, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (220, 104, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (221, 104, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (222, 105, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (223, 105, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (224, 105, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (225, 105, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (226, 106, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (227, 106, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (228, 106, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (229, 106, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (230, 109, 100, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (231, 109, 101, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (232, 109, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (233, 109, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (234, 110, 100, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (235, 110, 101, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (236, 110, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (237, 110, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (238, 112, 100, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (239, 112, 101, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (240, 112, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (241, 112, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (242, 96, 104, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (243, 96, 105, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (244, 96, 106, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (245, 96, 107, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (246, 97, 104, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (247, 97, 105, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (248, 97, 106, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (249, 97, 107, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (250, 98, 104, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (251, 98, 105, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (252, 98, 106, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (253, 98, 107, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (254, 99, 104, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (255, 99, 105, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (256, 99, 106, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (257, 99, 107, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (258, 85, 81, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (259, 85, 82, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (260, 85, 83, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (261, 115, 111, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (262, 115, 112, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (263, 115, 113, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (264, 116, 111, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (265, 116, 112, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (266, 116, 113, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (267, 117, 111, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (268, 117, 112, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (269, 117, 113, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (270, 118, 111, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (271, 118, 112, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (272, 118, 113, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (273, 120, 114, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (274, 120, 115, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (275, 120, 116, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (276, 121, 114, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (277, 121, 115, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (278, 121, 116, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (279, 122, 114, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (280, 122, 115, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (281, 122, 116, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (282, 88, 88, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (283, 88, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (284, 88, 90, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (285, 88, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (286, 89, 88, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (287, 89, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (288, 89, 90, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (289, 89, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (290, 90, 88, '10,8,9');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (291, 90, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (292, 90, 90, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (293, 90, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (294, 101, 92, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (295, 101, 93, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (296, 101, 94, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (297, 101, 95, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (298, 102, 92, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (299, 102, 93, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (300, 102, 94, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (301, 102, 95, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (302, 113, 100, 'A5,A6');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (303, 113, 101, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (304, 113, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (305, 113, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (306, 114, 100, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (307, 114, 101, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (308, 114, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (309, 114, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (310, 142, 124, '195/65 R15,205/55 R16,215/60 R17');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (311, 142, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (312, 142, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (313, 143, 124, '195/65 R15,205/55 R16,215/60 R17');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (314, 143, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (315, 143, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (316, 144, 124, '195/65 R15,205/55 R16,215/60 R17');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (317, 144, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (318, 144, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (319, 145, 124, '195/65 R15,205/55 R16,215/60 R17');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (320, 145, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (321, 145, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (322, 146, 124, '195/65 R15,205/55 R16,215/60 R17');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (323, 146, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (324, 146, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (325, 125, 117, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (326, 125, 118, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (327, 125, 119, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (328, 138, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (329, 138, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (330, 138, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (331, 139, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (332, 139, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (333, 139, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (334, 141, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (335, 141, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (336, 141, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (337, 151, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (338, 151, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (339, 151, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (340, 152, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (341, 152, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (342, 152, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (343, 1, 19, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (344, 1, 20, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (345, 1, 21, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (346, 1, 22, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (347, 1, 23, 'Advanced Dual Camera');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (348, 11, 24, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (349, 11, 25, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (350, 11, 26, 'Yes');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (351, 11, 27, '24 Hours');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (352, 21, 40, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (353, 21, 41, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (354, 21, 42, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (355, 21, 43, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (356, 31, 47, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (357, 31, 48, 'Black,White');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (358, 31, 49, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (359, 31, 50, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (360, 54, 51, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (361, 54, 52, '1.5L,2L');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (362, 54, 53, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (363, 54, 54, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (364, 40, 55, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (365, 40, 56, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (366, 40, 57, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (367, 42, 61, '4L,6L');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (368, 42, 62, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (369, 42, 63, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (370, 64, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (371, 64, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (372, 64, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (373, 64, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (374, 74, 68, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (375, 74, 69, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (376, 74, 70, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (377, 129, 108, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (378, 129, 109, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (379, 129, 110, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (380, 130, 108, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (381, 130, 109, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (382, 130, 110, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (383, 124, 114, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (384, 124, 115, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (385, 124, 116, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (386, 126, 117, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (387, 126, 118, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (388, 126, 119, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (389, 127, 117, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (390, 127, 118, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (391, 127, 119, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (392, 134, 120, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (393, 134, 121, '100ml,30ml,50ml');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (394, 134, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (395, 134, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (396, 135, 120, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (397, 135, 121, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (398, 135, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (399, 135, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (400, 136, 120, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (401, 136, 121, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (402, 136, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (403, 136, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (404, 137, 120, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (405, 137, 121, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (406, 137, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (407, 137, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (408, 86, 81, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (409, 86, 82, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (410, 86, 83, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (411, 107, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (412, 107, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (413, 107, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (414, 107, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (415, 111, 100, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (416, 111, 101, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (417, 111, 102, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (418, 111, 103, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (419, 119, 111, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (420, 119, 112, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (421, 119, 113, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (422, 123, 114, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (423, 123, 115, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (424, 123, 116, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (425, 128, 117, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (426, 128, 118, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (427, 128, 119, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (428, 140, 127, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (429, 140, 128, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (430, 140, 129, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (431, 8, 6, '16GB,32GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (432, 8, 7, '1TB,512GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (433, 8, 8, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (434, 8, 9, 'Latest Gen Processor');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (435, 8, 10, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (436, 6, 19, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (437, 6, 20, '128GB,256GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (438, 6, 21, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (439, 6, 22, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (440, 6, 23, 'Advanced Dual Camera');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (441, 37, 44, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (442, 37, 45, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (443, 37, 46, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (444, 38, 44, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (445, 38, 45, 'L,M,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (446, 38, 46, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (447, 55, 51, '24cm,26cm,28cm');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (448, 55, 52, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (449, 55, 53, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (450, 55, 54, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (451, 56, 51, '24cm,26cm,28cm');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (452, 56, 52, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (453, 56, 53, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (454, 56, 54, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (455, 50, 58, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (456, 50, 59, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (457, 50, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (458, 51, 58, '10L,15L');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (459, 51, 59, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (460, 51, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (461, 52, 58, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (462, 52, 59, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (463, 52, 60, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (464, 44, 61, '12-place,14-place');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (465, 44, 62, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (466, 44, 63, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (467, 65, 64, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (468, 65, 65, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (469, 65, 66, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (470, 65, 67, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (471, 84, 77, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (472, 84, 78, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (473, 84, 79, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (474, 84, 80, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (475, 83, 77, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (476, 83, 78, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (477, 83, 79, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (478, 83, 80, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (479, 87, 81, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (480, 87, 82, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (481, 87, 83, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (482, 92, 88, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (483, 92, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (484, 92, 90, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (485, 92, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (486, 93, 88, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (487, 93, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (488, 93, 90, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (489, 93, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (490, 94, 88, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (491, 94, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (492, 94, 90, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (493, 94, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (494, 108, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (495, 108, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (496, 108, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (497, 108, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (498, 103, 96, 'Hardcover,Kindle,Paperback');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (499, 103, 97, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (500, 103, 98, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (501, 103, 99, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (502, 132, 108, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (503, 132, 109, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (504, 132, 110, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (505, 133, 108, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (506, 133, 109, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (507, 133, 110, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (508, 131, 108, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (509, 131, 109, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (510, 131, 110, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (511, 150, 120, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (512, 150, 121, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (513, 150, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (514, 150, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (515, 149, 120, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (516, 149, 121, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (517, 149, 122, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (518, 149, 123, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (519, 9, 6, '16GB,32GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (520, 9, 7, '1TB,512GB');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (521, 9, 8, 'Black,Silver');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (522, 9, 9, 'Latest Gen Processor');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (523, 9, 10, 'Standard Size');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (524, 28, 36, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (525, 28, 37, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (526, 28, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (527, 28, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (528, 29, 36, 'L,M,S,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (529, 29, 37, 'Black');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (530, 29, 38, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (531, 29, 39, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (532, 57, 51, '24cm,26cm,28cm');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (533, 57, 52, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (534, 57, 53, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (535, 57, 54, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (536, 70, 71, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (537, 70, 72, 'Matte Finish');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (538, 70, 73, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (539, 95, 88, 'L,M,XL');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (540, 95, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (541, 95, 90, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (542, 95, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (543, 91, 88, '10,8,9');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (544, 91, 89, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (545, 91, 90, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (546, 91, 91, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (547, 147, 124, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (548, 147, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (549, 147, 126, 'Premium Material');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (550, 148, 124, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (551, 148, 125, 'Standard');
INSERT INTO pms_product_attribute_value (id, product_id, product_attribute_id, value) VALUES (552, 148, 126, 'Premium Material');
SELECT setval('pms_product_attribute_value_id_seq', (SELECT COALESCE(MAX(id), 1) FROM pms_product_attribute_value));