UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/1/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/1/banner.svg' WHERE id = 1;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/2/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/2/banner.svg' WHERE id = 2;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/3/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/3/banner.svg' WHERE id = 3;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/4/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/4/banner.svg' WHERE id = 4;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/5/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/5/banner.svg' WHERE id = 5;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/6/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/6/banner.svg' WHERE id = 6;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/7/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/7/banner.svg' WHERE id = 7;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/8/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/8/banner.svg' WHERE id = 8;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/9/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/9/banner.svg' WHERE id = 9;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/10/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/10/banner.svg' WHERE id = 10;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/11/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/11/banner.svg' WHERE id = 11;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/12/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/12/banner.svg' WHERE id = 12;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/13/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/13/banner.svg' WHERE id = 13;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/14/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/14/banner.svg' WHERE id = 14;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/15/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/15/banner.svg' WHERE id = 15;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/16/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/16/banner.svg' WHERE id = 16;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/17/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/17/banner.svg' WHERE id = 17;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/18/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/18/banner.svg' WHERE id = 18;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/19/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/19/banner.svg' WHERE id = 19;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/20/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/20/banner.svg' WHERE id = 20;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/21/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/21/banner.svg' WHERE id = 21;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/22/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/22/banner.svg' WHERE id = 22;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/23/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/23/banner.svg' WHERE id = 23;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/24/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/24/banner.svg' WHERE id = 24;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/25/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/25/banner.svg' WHERE id = 25;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/26/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/26/banner.svg' WHERE id = 26;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/27/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/27/banner.svg' WHERE id = 27;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/28/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/28/banner.svg' WHERE id = 28;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/29/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/29/banner.svg' WHERE id = 29;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/30/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/30/banner.svg' WHERE id = 30;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/31/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/31/banner.svg' WHERE id = 31;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/32/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/32/banner.svg' WHERE id = 32;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/33/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/33/banner.svg' WHERE id = 33;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/34/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/34/banner.svg' WHERE id = 34;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/35/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/35/banner.svg' WHERE id = 35;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/36/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/36/banner.svg' WHERE id = 36;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/37/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/37/banner.svg' WHERE id = 37;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/38/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/38/banner.svg' WHERE id = 38;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/39/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/39/banner.svg' WHERE id = 39;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/40/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/40/banner.svg' WHERE id = 40;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/41/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/41/banner.svg' WHERE id = 41;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/42/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/42/banner.svg' WHERE id = 42;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/43/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/43/banner.svg' WHERE id = 43;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/44/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/44/banner.svg' WHERE id = 44;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/45/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/45/banner.svg' WHERE id = 45;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/46/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/46/banner.svg' WHERE id = 46;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/47/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/47/banner.svg' WHERE id = 47;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/48/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/48/banner.svg' WHERE id = 48;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/49/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/49/banner.svg' WHERE id = 49;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/50/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/50/banner.svg' WHERE id = 50;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/51/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/51/banner.svg' WHERE id = 51;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/52/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/52/banner.svg' WHERE id = 52;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/53/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/53/banner.svg' WHERE id = 53;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/54/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/54/banner.svg' WHERE id = 54;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/55/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/55/banner.svg' WHERE id = 55;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/56/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/56/banner.svg' WHERE id = 56;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/57/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/57/banner.svg' WHERE id = 57;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/58/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/58/banner.svg' WHERE id = 58;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/59/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/59/banner.svg' WHERE id = 59;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/60/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/60/banner.svg' WHERE id = 60;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/61/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/61/banner.svg' WHERE id = 61;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/62/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/62/banner.svg' WHERE id = 62;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/63/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/63/banner.svg' WHERE id = 63;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/64/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/64/banner.svg' WHERE id = 64;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/65/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/65/banner.svg' WHERE id = 65;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/66/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/66/banner.svg' WHERE id = 66;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/67/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/67/banner.svg' WHERE id = 67;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/68/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/68/banner.svg' WHERE id = 68;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/69/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/69/banner.svg' WHERE id = 69;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/70/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/70/banner.svg' WHERE id = 70;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/71/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/71/banner.svg' WHERE id = 71;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/72/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/72/banner.svg' WHERE id = 72;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/73/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/73/banner.svg' WHERE id = 73;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/74/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/74/banner.svg' WHERE id = 74;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/75/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/75/banner.svg' WHERE id = 75;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/76/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/76/banner.svg' WHERE id = 76;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/77/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/77/banner.svg' WHERE id = 77;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/78/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/78/banner.svg' WHERE id = 78;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/79/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/79/banner.svg' WHERE id = 79;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/80/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/80/banner.svg' WHERE id = 80;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/81/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/81/banner.svg' WHERE id = 81;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/82/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/82/banner.svg' WHERE id = 82;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/83/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/83/banner.svg' WHERE id = 83;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/84/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/84/banner.svg' WHERE id = 84;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/85/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/85/banner.svg' WHERE id = 85;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/86/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/86/banner.svg' WHERE id = 86;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/87/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/87/banner.svg' WHERE id = 87;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/88/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/88/banner.svg' WHERE id = 88;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/89/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/89/banner.svg' WHERE id = 89;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/90/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/90/banner.svg' WHERE id = 90;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/91/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/91/banner.svg' WHERE id = 91;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/92/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/92/banner.svg' WHERE id = 92;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/93/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/93/banner.svg' WHERE id = 93;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/94/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/94/banner.svg' WHERE id = 94;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/95/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/95/banner.svg' WHERE id = 95;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/96/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/96/banner.svg' WHERE id = 96;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/97/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/97/banner.svg' WHERE id = 97;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/98/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/98/banner.svg' WHERE id = 98;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/99/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/99/banner.svg' WHERE id = 99;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/100/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/100/banner.svg' WHERE id = 100;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/101/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/101/banner.svg' WHERE id = 101;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/102/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/102/banner.svg' WHERE id = 102;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/103/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/103/banner.svg' WHERE id = 103;
UPDATE pms_brand SET logo = 'http://localhost:9000/nexus-media/public/catalog/brands/104/logo.svg', big_pic = 'http://localhost:9000/nexus-media/public/catalog/brands/104/banner.svg' WHERE id = 104;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/icon.svg' WHERE id = 1;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/2/icon.svg' WHERE id = 2;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/3/icon.svg' WHERE id = 3;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/4/icon.svg' WHERE id = 4;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/5/icon.svg' WHERE id = 5;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/6/icon.svg' WHERE id = 6;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/7/icon.svg' WHERE id = 7;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/8/icon.svg' WHERE id = 8;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/1/subcategories/9/icon.svg' WHERE id = 9;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/10/icon.svg' WHERE id = 10;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/10/subcategories/11/icon.svg' WHERE id = 11;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/10/subcategories/12/icon.svg' WHERE id = 12;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/10/subcategories/13/icon.svg' WHERE id = 13;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/10/subcategories/14/icon.svg' WHERE id = 14;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/15/icon.svg' WHERE id = 15;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/15/subcategories/16/icon.svg' WHERE id = 16;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/15/subcategories/17/icon.svg' WHERE id = 17;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/15/subcategories/18/icon.svg' WHERE id = 18;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/15/subcategories/19/icon.svg' WHERE id = 19;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/20/icon.svg' WHERE id = 20;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/20/subcategories/21/icon.svg' WHERE id = 21;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/20/subcategories/22/icon.svg' WHERE id = 22;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/20/subcategories/23/icon.svg' WHERE id = 23;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/20/subcategories/24/icon.svg' WHERE id = 24;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/25/icon.svg' WHERE id = 25;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/25/subcategories/26/icon.svg' WHERE id = 26;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/25/subcategories/27/icon.svg' WHERE id = 27;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/25/subcategories/28/icon.svg' WHERE id = 28;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/25/subcategories/29/icon.svg' WHERE id = 29;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/30/icon.svg' WHERE id = 30;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/30/subcategories/31/icon.svg' WHERE id = 31;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/30/subcategories/32/icon.svg' WHERE id = 32;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/30/subcategories/33/icon.svg' WHERE id = 33;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/30/subcategories/34/icon.svg' WHERE id = 34;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/35/icon.svg' WHERE id = 35;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/35/subcategories/36/icon.svg' WHERE id = 36;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/35/subcategories/37/icon.svg' WHERE id = 37;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/35/subcategories/38/icon.svg' WHERE id = 38;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/35/subcategories/39/icon.svg' WHERE id = 39;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/40/icon.svg' WHERE id = 40;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/40/subcategories/41/icon.svg' WHERE id = 41;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/40/subcategories/42/icon.svg' WHERE id = 42;
UPDATE pms_product_category SET icon = 'http://localhost:9000/nexus-media/public/catalog/categories/40/subcategories/43/icon.svg' WHERE id = 43;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/1/main.svg' WHERE id = 1;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/2/main.svg' WHERE id = 2;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/3/main.svg' WHERE id = 3;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/4/main.svg' WHERE id = 4;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/5/main.svg' WHERE id = 5;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/6/main.svg' WHERE id = 6;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/7/main.svg' WHERE id = 7;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/8/main.svg' WHERE id = 8;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/9/main.svg' WHERE id = 9;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/10/main.svg' WHERE id = 10;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/11/main.svg' WHERE id = 11;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/12/main.svg' WHERE id = 12;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/13/main.svg' WHERE id = 13;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/14/main.svg' WHERE id = 14;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/15/main.svg' WHERE id = 15;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/16/main.svg' WHERE id = 16;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/17/main.svg' WHERE id = 17;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/18/main.svg' WHERE id = 18;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/19/main.svg' WHERE id = 19;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/20/main.svg' WHERE id = 20;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/21/main.svg' WHERE id = 21;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/22/main.svg' WHERE id = 22;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/23/main.svg' WHERE id = 23;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/24/main.svg' WHERE id = 24;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/25/main.svg' WHERE id = 25;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/26/main.svg' WHERE id = 26;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/27/main.svg' WHERE id = 27;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/28/main.svg' WHERE id = 28;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/29/main.svg' WHERE id = 29;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/30/main.svg' WHERE id = 30;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/31/main.svg' WHERE id = 31;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/32/main.svg' WHERE id = 32;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/33/main.svg' WHERE id = 33;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/34/main.svg' WHERE id = 34;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/35/main.svg' WHERE id = 35;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/36/main.svg' WHERE id = 36;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/37/main.svg' WHERE id = 37;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/38/main.svg' WHERE id = 38;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/39/main.svg' WHERE id = 39;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/40/main.svg' WHERE id = 40;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/41/main.svg' WHERE id = 41;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/42/main.svg' WHERE id = 42;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/43/main.svg' WHERE id = 43;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/44/main.svg' WHERE id = 44;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/45/main.svg' WHERE id = 45;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/46/main.svg' WHERE id = 46;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/47/main.svg' WHERE id = 47;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/48/main.svg' WHERE id = 48;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/49/main.svg' WHERE id = 49;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/50/main.svg' WHERE id = 50;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/51/main.svg' WHERE id = 51;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/52/main.svg' WHERE id = 52;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/53/main.svg' WHERE id = 53;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/54/main.svg' WHERE id = 54;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/55/main.svg' WHERE id = 55;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/56/main.svg' WHERE id = 56;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/57/main.svg' WHERE id = 57;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/58/main.svg' WHERE id = 58;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/59/main.svg' WHERE id = 59;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/60/main.svg' WHERE id = 60;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/61/main.svg' WHERE id = 61;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/62/main.svg' WHERE id = 62;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/63/main.svg' WHERE id = 63;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/64/main.svg' WHERE id = 64;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/65/main.svg' WHERE id = 65;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/66/main.svg' WHERE id = 66;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/67/main.svg' WHERE id = 67;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/68/main.svg' WHERE id = 68;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/69/main.svg' WHERE id = 69;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/70/main.svg' WHERE id = 70;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/71/main.svg' WHERE id = 71;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/72/main.svg' WHERE id = 72;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/73/main.svg' WHERE id = 73;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/74/main.svg' WHERE id = 74;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/75/main.svg' WHERE id = 75;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/76/main.svg' WHERE id = 76;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/77/main.svg' WHERE id = 77;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/78/main.svg' WHERE id = 78;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/79/main.svg' WHERE id = 79;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/80/main.svg' WHERE id = 80;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/81/main.svg' WHERE id = 81;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/82/main.svg' WHERE id = 82;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/83/main.svg' WHERE id = 83;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/84/main.svg' WHERE id = 84;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/85/main.svg' WHERE id = 85;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/86/main.svg' WHERE id = 86;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/87/main.svg' WHERE id = 87;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/88/main.svg' WHERE id = 88;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/89/main.svg' WHERE id = 89;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/90/main.svg' WHERE id = 90;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/91/main.svg' WHERE id = 91;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/92/main.svg' WHERE id = 92;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/93/main.svg' WHERE id = 93;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/94/main.svg' WHERE id = 94;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/95/main.svg' WHERE id = 95;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/96/main.svg' WHERE id = 96;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/97/main.svg' WHERE id = 97;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/98/main.svg' WHERE id = 98;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/99/main.svg' WHERE id = 99;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/100/main.svg' WHERE id = 100;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/101/main.svg' WHERE id = 101;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/102/main.svg' WHERE id = 102;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/103/main.svg' WHERE id = 103;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/104/main.svg' WHERE id = 104;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/105/main.svg' WHERE id = 105;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/106/main.svg' WHERE id = 106;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/107/main.svg' WHERE id = 107;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/108/main.svg' WHERE id = 108;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/109/main.svg' WHERE id = 109;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/110/main.svg' WHERE id = 110;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/111/main.svg' WHERE id = 111;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/112/main.svg' WHERE id = 112;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/113/main.svg' WHERE id = 113;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/114/main.svg' WHERE id = 114;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/115/main.svg' WHERE id = 115;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/116/main.svg' WHERE id = 116;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/117/main.svg' WHERE id = 117;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/118/main.svg' WHERE id = 118;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/119/main.svg' WHERE id = 119;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/120/main.svg' WHERE id = 120;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/121/main.svg' WHERE id = 121;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/122/main.svg' WHERE id = 122;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/123/main.svg' WHERE id = 123;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/124/main.svg' WHERE id = 124;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/125/main.svg' WHERE id = 125;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/126/main.svg' WHERE id = 126;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/127/main.svg' WHERE id = 127;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/128/main.svg' WHERE id = 128;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/129/main.svg' WHERE id = 129;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/130/main.svg' WHERE id = 130;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/131/main.svg' WHERE id = 131;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/132/main.svg' WHERE id = 132;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/133/main.svg' WHERE id = 133;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/134/main.svg' WHERE id = 134;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/135/main.svg' WHERE id = 135;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/136/main.svg' WHERE id = 136;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/137/main.svg' WHERE id = 137;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/138/main.svg' WHERE id = 138;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/139/main.svg' WHERE id = 139;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/140/main.svg' WHERE id = 140;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/141/main.svg' WHERE id = 141;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/142/main.svg' WHERE id = 142;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/143/main.svg' WHERE id = 143;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/144/main.svg' WHERE id = 144;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/145/main.svg' WHERE id = 145;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/146/main.svg' WHERE id = 146;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/147/main.svg' WHERE id = 147;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/148/main.svg' WHERE id = 148;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/149/main.svg' WHERE id = 149;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/150/main.svg' WHERE id = 150;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/151/main.svg' WHERE id = 151;
UPDATE pms_product SET pic = 'http://localhost:9000/nexus-media/public/catalog/products/152/main.svg' WHERE id = 152;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APPLE-IP17-BLK-128/main.svg' WHERE id = 1;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APPLE-IP17-BLK-256/main.svg' WHERE id = 2;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APPLE-IP17-SLV-128/main.svg' WHERE id = 3;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APPLE-IP17-SLV-256/main.svg' WHERE id = 4;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-GS26-BLK-128/main.svg' WHERE id = 5;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-GS26-BLK-256/main.svg' WHERE id = 6;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-GS26-SLV-128/main.svg' WHERE id = 7;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-GS26-SLV-256/main.svg' WHERE id = 8;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/GOOGLE-PX11-BLK-128/main.svg' WHERE id = 9;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/GOOGLE-PX11-BLK-256/main.svg' WHERE id = 10;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/GOOGLE-PX11-SLV-128/main.svg' WHERE id = 11;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/GOOGLE-PX11-SLV-256/main.svg' WHERE id = 12;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAVA-TAB11-BLK-128/main.svg' WHERE id = 13;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAVA-TAB11-BLK-256/main.svg' WHERE id = 14;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAVA-TAB11-SLV-128/main.svg' WHERE id = 15;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAVA-TAB11-SLV-256/main.svg' WHERE id = 16;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OP14-BLK-128/main.svg' WHERE id = 17;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OP14-BLK-256/main.svg' WHERE id = 18;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OP14-SLV-128/main.svg' WHERE id = 19;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OP14-SLV-256/main.svg' WHERE id = 20;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICRO-INN3-BLK-128/main.svg' WHERE id = 21;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICRO-INN3-BLK-256/main.svg' WHERE id = 22;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICRO-INN3-SLV-128/main.svg' WHERE id = 23;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICRO-INN3-SLV-256/main.svg' WHERE id = 24;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DELL-IN16P-16-512-BLK/main.svg' WHERE id = 25;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DELL-IN16P-16-1TB-SLV/main.svg' WHERE id = 26;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DELL-IN16P-32-1TB-BLK/main.svg' WHERE id = 27;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DELL-IN16P-32-1TB-SLV/main.svg' WHERE id = 28;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LENOVO-TPE16-16-512-BLK/main.svg' WHERE id = 29;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LENOVO-TPE16-16-1TB-SLV/main.svg' WHERE id = 30;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LENOVO-TPE16-32-1TB-BLK/main.svg' WHERE id = 31;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LENOVO-TPE16-32-1TB-SLV/main.svg' WHERE id = 32;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ASUS-VBS16-16-512-BLK/main.svg' WHERE id = 33;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ASUS-VBS16-16-1TB-SLV/main.svg' WHERE id = 34;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ASUS-VBS16-32-1TB-BLK/main.svg' WHERE id = 35;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ASUS-VBS16-32-1TB-SLV/main.svg' WHERE id = 36;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OPPAD3-BLK-128/main.svg' WHERE id = 37;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OPPAD3-BLK-256/main.svg' WHERE id = 38;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OPPAD3-SLV-128/main.svg' WHERE id = 39;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ONEPLUS-OPPAD3-SLV-256/main.svg' WHERE id = 40;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PORT-MUFFM2-BLK/main.svg' WHERE id = 41;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PORT-MUFFM2-SLV/main.svg' WHERE id = 42;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NOTHING-EAR3-BLK/main.svg' WHERE id = 43;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NOTHING-EAR3-SLV/main.svg' WHERE id = 44;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NOISE-BXPR-BLK/main.svg' WHERE id = 45;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOAT-LUNPRO-BLK/main.svg' WHERE id = 46;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOAT-LUNPRO-SLV/main.svg' WHERE id = 47;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOGI-MXBRIO-STD/main.svg' WHERE id = 48;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SONY-WH6-BLK/main.svg' WHERE id = 49;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SONY-WH6-SLV/main.svg' WHERE id = 50;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LG-27GS6-27-QHD/main.svg' WHERE id = 51;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LG-27GS6-32-4K/main.svg' WHERE id = 52;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-ODG6-27-QHD/main.svg' WHERE id = 53;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SAMSUNG-ODG6-32-4K/main.svg' WHERE id = 54;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZEBRO-TWK-BLK/main.svg' WHERE id = 55;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZEBRO-TWK-SLV/main.svg' WHERE id = 56;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LEVIS-511SL-S-BLK/main.svg' WHERE id = 57;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LEVIS-511SL-M-BLK/main.svg' WHERE id = 58;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LEVIS-511SL-L-BLK/main.svg' WHERE id = 59;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LEVIS-511SL-XL-BLK/main.svg' WHERE id = 60;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ALLENS-ASOXR-S-BLK/main.svg' WHERE id = 61;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ALLENS-ASOXR-M-BLK/main.svg' WHERE id = 62;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ALLENS-ASOXR-L-BLK/main.svg' WHERE id = 63;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ALLENS-ASOXR-XL-BLK/main.svg' WHERE id = 64;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PETEREN-PEFSH-S-BLK/main.svg' WHERE id = 65;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PETEREN-PEFSH-M-BLK/main.svg' WHERE id = 66;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PETEREN-PEFSH-L-BLK/main.svg' WHERE id = 67;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PETEREN-PEFSH-XL-BLK/main.svg' WHERE id = 68;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYMOND-RFT-S-BLK/main.svg' WHERE id = 69;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYMOND-RFT-M-BLK/main.svg' WHERE id = 70;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYMOND-RFT-L-BLK/main.svg' WHERE id = 71;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYMOND-RFT-XL-BLK/main.svg' WHERE id = 72;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNIQLO-UQT-M/main.svg' WHERE id = 73;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNIQLO-UQT-L/main.svg' WHERE id = 74;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNIQLO-UQT-XL/main.svg' WHERE id = 75;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZARA-ZRBL-S-BLK/main.svg' WHERE id = 76;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZARA-ZRBL-M-BLK/main.svg' WHERE id = 77;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZARA-ZRBL-L-BLK/main.svg' WHERE id = 78;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ZARA-ZRBL-XL-BLK/main.svg' WHERE id = 79;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HM-HMD-S-BLK/main.svg' WHERE id = 80;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HM-HMD-M-BLK/main.svg' WHERE id = 81;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HM-HMD-L-BLK/main.svg' WHERE id = 82;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HM-HMD-XL-BLK/main.svg' WHERE id = 83;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FABIND-FBKRT-S-BLK/main.svg' WHERE id = 84;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FABIND-FBKRT-M-BLK/main.svg' WHERE id = 85;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FABIND-FBKRT-L-BLK/main.svg' WHERE id = 86;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FABIND-FBKRT-XL-BLK/main.svg' WHERE id = 87;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MANYAVAR-MVKRT-S-BLK/main.svg' WHERE id = 88;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAWKINS-CONT-5L/main.svg' WHERE id = 137;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MANYAVAR-MVKRT-M-BLK/main.svg' WHERE id = 89;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MANYAVAR-MVKRT-L-BLK/main.svg' WHERE id = 90;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MANYAVAR-MVKRT-XL-BLK/main.svg' WHERE id = 91;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WFW-WKS-S-BLK/main.svg' WHERE id = 92;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WFW-WKS-M-BLK/main.svg' WHERE id = 93;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WFW-WKS-L-BLK/main.svg' WHERE id = 94;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WFW-WKS-XL-BLK/main.svg' WHERE id = 95;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-AM270-BLK-8/main.svg' WHERE id = 96;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-AM270-BLK-9/main.svg' WHERE id = 97;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-AM270-WHT-8/main.svg' WHERE id = 98;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-AM270-WHT-9/main.svg' WHERE id = 99;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-UBLGT-BLK-8/main.svg' WHERE id = 100;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-UBLGT-BLK-9/main.svg' WHERE id = 101;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-UBLGT-WHT-8/main.svg' WHERE id = 102;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-UBLGT-WHT-9/main.svg' WHERE id = 103;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PUMA-VN3-BLK-8/main.svg' WHERE id = 104;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PUMA-VN3-BLK-9/main.svg' WHERE id = 105;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PUMA-VN3-WHT-8/main.svg' WHERE id = 106;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PUMA-VN3-WHT-9/main.svg' WHERE id = 107;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TNF-VEND-BLK-8/main.svg' WHERE id = 108;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TNF-VEND-BLK-9/main.svg' WHERE id = 109;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TNF-VEND-WHT-8/main.svg' WHERE id = 110;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TNF-VEND-WHT-9/main.svg' WHERE id = 111;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYBAN-AVCL-BLK/main.svg' WHERE id = 112;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RAYBAN-AVCL-SLV/main.svg' WHERE id = 113;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VANH-VHBLT-S/main.svg' WHERE id = 114;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VANH-VHBLT-M/main.svg' WHERE id = 115;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VANH-VHBLT-L/main.svg' WHERE id = 116;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNIQLO-RMSB-BLK/main.svg' WHERE id = 117;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNIQLO-RMSB-SLV/main.svg' WHERE id = 118;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-HBPK-BLK/main.svg' WHERE id = 119;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIKE-HBPK-SLV/main.svg' WHERE id = 120;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-3SCAP-M/main.svg' WHERE id = 121;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-3SCAP-L/main.svg' WHERE id = 122;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ADIDAS-3SCAP-XL/main.svg' WHERE id = 123;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/IKEA-MALM6-STD/main.svg' WHERE id = 124;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/IKEA-LACK-BLK/main.svg' WHERE id = 125;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/IKEA-LACK-SLV/main.svg' WHERE id = 126;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/IKEA-BILLY-BLK/main.svg' WHERE id = 127;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/IKEA-BILLY-SLV/main.svg' WHERE id = 128;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PHILIPS-AF3K-4L/main.svg' WHERE id = 129;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PHILIPS-AF3K-6L/main.svg' WHERE id = 130;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DYSON-V15D-STD/main.svg' WHERE id = 131;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCH-BOSDW-12P/main.svg' WHERE id = 132;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCH-BOSDW-14P/main.svg' WHERE id = 133;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRESTIGE-AFPRO-4L/main.svg' WHERE id = 134;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRESTIGE-AFPRO-6L/main.svg' WHERE id = 135;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAWKINS-CONT-3L/main.svg' WHERE id = 136;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/KENT-KGR-STD/main.svg' WHERE id = 138;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LG-LGW65-6.5KG/main.svg' WHERE id = 139;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LG-LGW65-8KG/main.svg' WHERE id = 140;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCH-BOS8-6.5KG/main.svg' WHERE id = 141;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCH-BOS8-8KG/main.svg' WHERE id = 142;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BAJAJ-MTF-BLK/main.svg' WHERE id = 143;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BAJAJ-MTF-SLV/main.svg' WHERE id = 144;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAVELLS-AQP-10L/main.svg' WHERE id = 145;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAVELLS-AQP-15L/main.svg' WHERE id = 146;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/USHA-MAF-BLK/main.svg' WHERE id = 147;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/USHA-MAF-SLV/main.svg' WHERE id = 148;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BUTTERFLY-RB3-STD/main.svg' WHERE id = 149;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CROMPTON-SEK-1.5L/main.svg' WHERE id = 150;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CROMPTON-SEK-2L/main.svg' WHERE id = 151;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WONDERCHEF-GFP-24CM/main.svg' WHERE id = 152;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WONDERCHEF-GFP-26CM/main.svg' WHERE id = 153;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WONDERCHEF-GFP-28CM/main.svg' WHERE id = 154;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRESTIGE-ODP-24CM/main.svg' WHERE id = 155;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRESTIGE-ODP-26CM/main.svg' WHERE id = 156;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRESTIGE-ODP-28CM/main.svg' WHERE id = 157;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAWKINS-FNT-24CM/main.svg' WHERE id = 158;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAWKINS-FNT-26CM/main.svg' WHERE id = 159;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/HAWKINS-FNT-28CM/main.svg' WHERE id = 160;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ORDINARY-NOZ-STD/main.svg' WHERE id = 161;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVEA-NSOFT-30ML/main.svg' WHERE id = 162;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVEA-NSOFT-50ML/main.svg' WHERE id = 163;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CLINIQUE-MS100-30ML/main.svg' WHERE id = 164;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CLINIQUE-MS100-50ML/main.svg' WHERE id = 165;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CLINIQUE-MS100-100ML/main.svg' WHERE id = 166;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NEUTRO-HWB-30ML/main.svg' WHERE id = 167;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NEUTRO-HWB-50ML/main.svg' WHERE id = 168;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NEUTRO-HWB-100ML/main.svg' WHERE id = 169;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAMAEARTH-VCFS-STD/main.svg' WHERE id = 170;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MINIMAL-SA2-STD/main.svg' WHERE id = 171;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FOREST-FTM-30ML/main.svg' WHERE id = 172;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FOREST-FTM-50ML/main.svg' WHERE id = 173;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FOREST-FTM-100ML/main.svg' WHERE id = 174;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTFW-30ML/main.svg' WHERE id = 175;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTFW-50ML/main.svg' WHERE id = 176;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTFW-100ML/main.svg' WHERE id = 177;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-TMatch-110/main.svg' WHERE id = 178;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-TMatch-120/main.svg' WHERE id = 179;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-TMatch-130/main.svg' WHERE id = 180;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-TMatch-220/main.svg' WHERE id = 181;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAYBELLINE-FMF-110/main.svg' WHERE id = 182;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAYBELLINE-FMF-120/main.svg' WHERE id = 183;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAYBELLINE-FMF-130/main.svg' WHERE id = 184;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAYBELLINE-FMF-220/main.svg' WHERE id = 185;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAKME-9T5-110/main.svg' WHERE id = 186;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAKME-9T5-120/main.svg' WHERE id = 187;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAKME-9T5-130/main.svg' WHERE id = 188;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LAKME-9T5-220/main.svg' WHERE id = 189;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-SKGEN-110/main.svg' WHERE id = 190;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-SKGEN-120/main.svg' WHERE id = 191;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-SKGEN-130/main.svg' WHERE id = 192;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-SKGEN-220/main.svg' WHERE id = 193;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BIOTIQUE-BCC-30ML/main.svg' WHERE id = 194;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BIOTIQUE-BCC-50ML/main.svg' WHERE id = 195;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BIOTIQUE-BCC-100ML/main.svg' WHERE id = 196;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DOVE-DIR-30ML/main.svg' WHERE id = 197;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DOVE-DIR-50ML/main.svg' WHERE id = 198;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DOVE-DIR-100ML/main.svg' WHERE id = 199;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-ARS-30ML/main.svg' WHERE id = 200;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-ARS-50ML/main.svg' WHERE id = 201;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/LOREAL-ARS-100ML/main.svg' WHERE id = 202;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAMAEARTH-OHO-30ML/main.svg' WHERE id = 203;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAMAEARTH-OHO-50ML/main.svg' WHERE id = 204;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MAMAEARTH-OHO-100ML/main.svg' WHERE id = 205;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVEA-MSG-30ML/main.svg' WHERE id = 206;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVEA-MSG-50ML/main.svg' WHERE id = 207;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVEA-MSG-100ML/main.svg' WHERE id = 208;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-MBW-30ML/main.svg' WHERE id = 209;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-MBW-50ML/main.svg' WHERE id = 210;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NYKAA-MBW-100ML/main.svg' WHERE id = 211;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTSG-30ML/main.svg' WHERE id = 212;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTSG-50ML/main.svg' WHERE id = 213;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PLUM-GTSG-100ML/main.svg' WHERE id = 214;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UA-CA10-BLK-8/main.svg' WHERE id = 215;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UA-CA10-BLK-9/main.svg' WHERE id = 216;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UA-CA10-WHT-8/main.svg' WHERE id = 217;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UA-CA10-WHT-9/main.svg' WHERE id = 218;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-KRC-BLK-8/main.svg' WHERE id = 219;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-KRC-BLK-9/main.svg' WHERE id = 220;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-KRC-WHT-8/main.svg' WHERE id = 221;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-KRC-WHT-9/main.svg' WHERE id = 222;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-RACER-BLK-8/main.svg' WHERE id = 223;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-RACER-BLK-9/main.svg' WHERE id = 224;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-RACER-WHT-8/main.svg' WHERE id = 225;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-RACER-WHT-9/main.svg' WHERE id = 226;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-SPRINT-BLK-8/main.svg' WHERE id = 227;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-SPRINT-BLK-9/main.svg' WHERE id = 228;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-SPRINT-WHT-8/main.svg' WHERE id = 229;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-SPRINT-WHT-9/main.svg' WHERE id = 230;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-ADJDB-STD/main.svg' WHERE id = 231;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-HD10-STD/main.svg' WHERE id = 232;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COSCO-RTSET-STD/main.svg' WHERE id = 233;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-PTG-M/main.svg' WHERE id = 234;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-PTG-L/main.svg' WHERE id = 235;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/VECTORX-PTG-XL/main.svg' WHERE id = 236;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-BYM-BLK/main.svg' WHERE id = 237;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-BYM-SLV/main.svg' WHERE id = 238;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-TPEM-BLK/main.svg' WHERE id = 239;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-TPEM-SLV/main.svg' WHERE id = 240;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COSCO-YBP-BLK/main.svg' WHERE id = 241;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COSCO-YBP-SLV/main.svg' WHERE id = 242;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WILSON-PS97-STD/main.svg' WHERE id = 243;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/YONEX-A100Z-STD/main.svg' WHERE id = 244;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SS-SSKYER-S8/main.svg' WHERE id = 245;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SS-SSKYER-S9/main.svg' WHERE id = 246;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SS-SSKYER-S10/main.svg' WHERE id = 247;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SG-SGP-S8/main.svg' WHERE id = 248;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SG-SGP-S9/main.svg' WHERE id = 249;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SG-SGP-S10/main.svg' WHERE id = 250;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-QHB40-BLK/main.svg' WHERE id = 251;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DECATHLON-QHB40-SLV/main.svg' WHERE id = 252;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NIVIA-STORM-STD/main.svg' WHERE id = 253;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COSCO-CVB-STD/main.svg' WHERE id = 254;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WILSON-NBAOB-M/main.svg' WHERE id = 255;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WILSON-NBAOB-L/main.svg' WHERE id = 256;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/WILSON-NBAOB-XL/main.svg' WHERE id = 257;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-MNL-PB/main.svg' WHERE id = 258;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-MNL-HC/main.svg' WHERE id = 259;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-MNL-KD/main.svg' WHERE id = 260;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-1984-PB/main.svg' WHERE id = 261;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-1984-HC/main.svg' WHERE id = 262;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-1984-KD/main.svg' WHERE id = 263;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RUPA-TSP-PB/main.svg' WHERE id = 264;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RUPA-TSP-HC/main.svg' WHERE id = 265;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RUPA-TSP-KD/main.svg' WHERE id = 266;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ACK-MHB-PB/main.svg' WHERE id = 267;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ACK-MHB-HC/main.svg' WHERE id = 268;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ACK-MHB-KD/main.svg' WHERE id = 269;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-AH-PB/main.svg' WHERE id = 270;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-AH-HC/main.svg' WHERE id = 271;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-AH-KD/main.svg' WHERE id = 272;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-TLS-PB/main.svg' WHERE id = 273;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-TLS-HC/main.svg' WHERE id = 274;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-TLS-KD/main.svg' WHERE id = 275;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-SSG-PB/main.svg' WHERE id = 276;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-SSG-HC/main.svg' WHERE id = 277;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-SSG-KD/main.svg' WHERE id = 278;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-CC-PB/main.svg' WHERE id = 279;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-CC-HC/main.svg' WHERE id = 280;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-CC-KD/main.svg' WHERE id = 281;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-DDIA-PB/main.svg' WHERE id = 282;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-DDIA-HC/main.svg' WHERE id = 283;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/OREILLY-DDIA-KD/main.svg' WHERE id = 284;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-CCIT-PB/main.svg' WHERE id = 285;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-CCIT-HC/main.svg' WHERE id = 286;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MCGRAW-CCIT-KD/main.svg' WHERE id = 287;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-JPC-PB/main.svg' WHERE id = 288;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-JPC-HC/main.svg' WHERE id = 289;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PEARSON-JPC-KD/main.svg' WHERE id = 290;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SCHAND-DSC-PB/main.svg' WHERE id = 291;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SCHAND-DSC-HC/main.svg' WHERE id = 292;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SCHAND-DSC-KD/main.svg' WHERE id = 293;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ARIHANT-PYCP-PB/main.svg' WHERE id = 294;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ARIHANT-PYCP-HC/main.svg' WHERE id = 295;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ARIHANT-PYCP-KD/main.svg' WHERE id = 296;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOLESKINE-MKNL-STD/main.svg' WHERE id = 297;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CROSSWORD-PRN-BLK/main.svg' WHERE id = 298;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CROSSWORD-PRN-SLV/main.svg' WHERE id = 299;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RUPA-EXJ-BLK/main.svg' WHERE id = 300;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/RUPA-EXJ-SLV/main.svg' WHERE id = 301;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/SCHAND-GPN-STD/main.svg' WHERE id = 302;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ARIHANT-EPN-A6/main.svg' WHERE id = 303;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ARIHANT-EPN-A5/main.svg' WHERE id = 304;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PRH-RDJ-STD/main.svg' WHERE id = 305;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-NCF-100G/main.svg' WHERE id = 306;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-NCF-200G/main.svg' WHERE id = 307;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-NCF-500G/main.svg' WHERE id = 308;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COKE-COKE-300ML/main.svg' WHERE id = 309;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COKE-COKE-750ML/main.svg' WHERE id = 310;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COKE-COKE-1.25L/main.svg' WHERE id = 311;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/COKE-COKE-2.25L/main.svg' WHERE id = 312;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AMUL-ATMLK-500ML/main.svg' WHERE id = 313;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AMUL-ATMLK-1L/main.svg' WHERE id = 314;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-TTG-100G/main.svg' WHERE id = 315;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-TTG-200G/main.svg' WHERE id = 316;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-TTG-500G/main.svg' WHERE id = 317;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-TDMLK-500ML/main.svg' WHERE id = 318;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-TDMLK-1L/main.svg' WHERE id = 319;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-TDMLK-2L/main.svg' WHERE id = 320;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BRITANNIA-GDC-100G/main.svg' WHERE id = 321;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BRITANNIA-GDC-200G/main.svg' WHERE id = 322;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BRITANNIA-GDC-500G/main.svg' WHERE id = 323;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PARLE-HSB-100G/main.svg' WHERE id = 324;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PARLE-HSB-200G/main.svg' WHERE id = 325;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PARLE-HSB-500G/main.svg' WHERE id = 326;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ITC-SDF-100G/main.svg' WHERE id = 327;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ITC-SDF-200G/main.svg' WHERE id = 328;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/ITC-SDF-500G/main.svg' WHERE id = 329;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-MUNCH-100G/main.svg' WHERE id = 330;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-MUNCH-200G/main.svg' WHERE id = 331;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/NESTLE-MUNCH-500G/main.svg' WHERE id = 332;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DABUR-REAL-500ML/main.svg' WHERE id = 333;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DABUR-REAL-1L/main.svg' WHERE id = 334;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/DABUR-REAL-2L/main.svg' WHERE id = 335;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/KELLOGG-KCF-100G/main.svg' WHERE id = 336;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/KELLOGG-KCF-200G/main.svg' WHERE id = 337;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/KELLOGG-KCF-500G/main.svg' WHERE id = 338;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MTR-MPOHA-100G/main.svg' WHERE id = 339;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MTR-MPOHA-200G/main.svg' WHERE id = 340;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MTR-MPOHA-500G/main.svg' WHERE id = 341;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AASHIRVAAD-MGA-100G/main.svg' WHERE id = 342;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AASHIRVAAD-MGA-200G/main.svg' WHERE id = 343;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AASHIRVAAD-MGA-500G/main.svg' WHERE id = 344;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-SPOHA-100G/main.svg' WHERE id = 345;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-SPOHA-200G/main.svg' WHERE id = 346;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TATA-SPOHA-500G/main.svg' WHERE id = 347;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FORTUNE-FSO-500ML/main.svg' WHERE id = 348;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FORTUNE-FSO-1L/main.svg' WHERE id = 349;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/FORTUNE-FSO-2L/main.svg' WHERE id = 350;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PATANJALI-DALIA-100G/main.svg' WHERE id = 351;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PATANJALI-DALIA-200G/main.svg' WHERE id = 352;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/PATANJALI-DALIA-500G/main.svg' WHERE id = 353;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNILEVER-KTK-500ML/main.svg' WHERE id = 354;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNILEVER-KTK-1L/main.svg' WHERE id = 355;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/UNILEVER-KTK-2L/main.svg' WHERE id = 356;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AMUL-PGHEE-500ML/main.svg' WHERE id = 357;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AMUL-PGHEE-1L/main.svg' WHERE id = 358;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/AMUL-PGHEE-2L/main.svg' WHERE id = 359;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-PANEER-100G/main.svg' WHERE id = 360;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-PANEER-200G/main.svg' WHERE id = 361;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTHERDAIRY-PANEER-500G/main.svg' WHERE id = 362;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-MFC-30ML/main.svg' WHERE id = 363;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-MFC-50ML/main.svg' WHERE id = 364;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-MFC-100ML/main.svg' WHERE id = 365;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCHI-CAF-STD/main.svg' WHERE id = 366;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TVS-CBC-STD/main.svg' WHERE id = 367;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CEAT-TVK-STD/main.svg' WHERE id = 368;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CASTROL-MAG530-STD/main.svg' WHERE id = 369;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTUL-XCESS-STD/main.svg' WHERE id = 370;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/GULF-FG530-STD/main.svg' WHERE id = 371;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-PRIT-30ML/main.svg' WHERE id = 372;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-PRIT-50ML/main.svg' WHERE id = 373;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-PRIT-100ML/main.svg' WHERE id = 374;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICHELIN-XM2P-R15/main.svg' WHERE id = 375;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICHELIN-XM2P-R16/main.svg' WHERE id = 376;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MICHELIN-XM2P-R17/main.svg' WHERE id = 377;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MRF-PERF-R15/main.svg' WHERE id = 378;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MRF-PERF-R16/main.svg' WHERE id = 379;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MRF-PERF-R17/main.svg' WHERE id = 380;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APOLLO-ALN4-R15/main.svg' WHERE id = 381;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APOLLO-ALN4-R16/main.svg' WHERE id = 382;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/APOLLO-ALN4-R17/main.svg' WHERE id = 383;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CEAT-MILAZE-R15/main.svg' WHERE id = 384;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CEAT-MILAZE-R16/main.svg' WHERE id = 385;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CEAT-MILAZE-R17/main.svg' WHERE id = 386;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TVS-EGRIP-R15/main.svg' WHERE id = 387;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TVS-EGRIP-R16/main.svg' WHERE id = 388;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TVS-EGRIP-R17/main.svg' WHERE id = 389;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/BOSCHI-PSP-STD/main.svg' WHERE id = 390;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CEAT-CBPS-STD/main.svg' WHERE id = 391;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-CVC-BLK/main.svg' WHERE id = 392;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/3M-CVC-SLV/main.svg' WHERE id = 393;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/TVS-PTI-STD/main.svg' WHERE id = 394;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CASTROL-EF-30ML/main.svg' WHERE id = 395;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CASTROL-EF-50ML/main.svg' WHERE id = 396;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/CASTROL-EF-100ML/main.svg' WHERE id = 397;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTUL-CCLEAN-30ML/main.svg' WHERE id = 398;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTUL-CCLEAN-50ML/main.svg' WHERE id = 399;
UPDATE pms_sku_stock SET pic = 'http://localhost:9000/nexus-media/public/catalog/skus/MOTUL-CCLEAN-100ML/main.svg' WHERE id = 400;